### ISSUE TITLE
Middleware Cannot access the Database.

### ISSUE THREAD

**Issue by bshivam4** [fidanzaEPSI/slim3-starter#1]
When I try to access the Database from a middleware. I get the following error:- 

**Details**

Type: Error
Message: Call to a member function connection() on null
File:  .................../vendor/illuminate/database/Eloquent/Model.php
Line: 1041

**Comment by fidanf** [comment]
You need to pass the Eloquent class as a dependency into your middleware's constructor or you can just add it to the protected properties of the parent Middleware.

**Comment by bshivam4** [comment]
I tried with the same, but couldn't solve it.
Can you please provide the code to do the same?

**Comment by fidanf** [comment]
You were right. There was a line of code missing in App.php to set Eloquent as global in order to be able to use the QueryBuilder.

After that I tried the following middleware and it worked :


Class DBMiddleware extends Middleware
{

    public function __invoke(Request $request, Response $response, callable $next)
    {
        debug($this->db->table('users')->select('*')->get());

        $response = $next($request, $response);
        return $response;
    }
}

**Comment by bshivam4** [comment]
Solved!
Thanks buddy.
