### ISSUE TITLE
CSRF protection, cant trigger 403 false response

### ISSUE THREAD

**Issue by sarelvdm** [fidanzaEPSI/slim3-starter#2]
Hi,
I installed the package all working except that I cant trigger the CSRF false response 

if($request->getAttribute('csrf_status') === false) {
            return $this->view->render($response->withStatus(403), '/errors/403.twig');
        } else {
            echo "key validated";
        }

**Comment by sarelvdm** [comment]
Hi, can you please contact me... need to understand the logic when using REDIS, do you try and share sessions across different servers or domains

**Comment by fidanf** [comment]
Redis serves the purpose of caching SQL queries stored in json format inside a redis-server. Basically what happen is : 
- User requests records, backend asks mysql for records and serves them to the user, while storing them inside redis at the same time
- User then requests the same records while the cached key is still active : now the backend directly serves from redis-server and not a single SQL request is being made. This saves a lot of performance when serving huge records repeatedly.

If you wanna test it, you should run the project inside a vagrant/homestead box environment which comes with both redis-server and redis-client listening on port 6379 by default.

Hope this helped!

**Comment by sarelvdm** [comment]
Thanks for responding, I will look into Redis, Im on Win 10 using wsl ubuntu.

Any other way we can chat, i value your time and don't what to bug you unnecessary. Just a couple of short questions regarding the logic in the slim3-starter.

**Comment by fidanf** [comment]
Sure :) You can message me on fidanza.frank@gmail.com.

**Comment by sarelvdm** [comment]
Thanks, will do tomorrow. Need to go and sleep,
